### ISSUE TITLE
Lose stack trace?

### ISSUE THREAD

**Issue by brandonros** [request/request-promise-native#44]
```
StatusCodeError: 500 - "Internal error"
    at new StatusCodeError (/app/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/app/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/app/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/app/node_modules/request/request.js:185:22)
    at Request.emit (events.js:182:13)
    at Request.EventEmitter.emit (domain.js:441:20)
    at Request.<anonymous> (/app/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:182:13)
    at Request.EventEmitter.emit (domain.js:441:20)
    at IncomingMessage.<anonymous> (/app/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:273:13)
    at IncomingMessage.emit (events.js:187:15)
    at IncomingMessage.EventEmitter.emit (domain.js:441:20)
    at endReadableNT (_stream_readable.js:1094:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

I get this as a stack trace.

Notice how, it doesn't tell me the original function that called `rp.get(options)` for example.

aka I can't tell which of my many API requests is failing.

I know this is probably a known issue/mentioned somewhere else. What's the workaround/fix for this? Does the problem go all the way back to `request-promise-core` or even `request` itself?

I'm using `    "request-promise-native": "^1.0.5",` but I'm willing to bet it's happening in any/all versions?

**Comment by eremzeit** [comment]
I can confirm that I'm experiencing this problem as well.  There was another issue opened for this that got closed https://github.com/request/request-promise/issues/184.  But I don't think the issue was really addressed. 

Other asynchronous request libraries don't end up clobbering the stack trace like request promise does.  Seems like a bug.

**Comment by brandonros** [comment]
I think it’s a node.js -> V8 async function stack trace thing. I moved to node-fetch for what it is worth.
