### ISSUE TITLE
"getaddrinfo ENOTFOUND" error

### ISSUE THREAD

**Issue by tyleri** [request/request-promise-native#6]
I recently came across this issue when using request-promise-native. When sending a GET or POST request to certain URLs, I received a "getaddrinfo ENOTFOUND" error. This seems to happen randomly (i.e. some URL requests would throw this error during one run but work completely fine on the next). After some Googling, I found this issue:

https://github.com/nodejs/node/issues/5436#issuecomment-189600282

Although I didn't find this documented in the request-promise page, I added {"family": 4} to the options, and I stopped getting the error. It might be useful to either set "family" to 4 by default or just make a note of this in the documentation.

**Comment by analog-nico** [comment]
Thank you @tyleri , this is an immensely useful tweak!

I wouldn't set this option by default because of the unwanted effects it may cause for existing `request-promise` / `request-promise-native` users. However, I'll add this to the docs. Maybe a "troubleshooting" section would make sense.

I'll keep this issue open until I updated the docs.

**Comment by olexme** [comment]
I have similar issue. I get the err like below (theurl.com is a placeholder) after a few hours of request-promise package usage and hundreds of requests pointing the same 'theurl.com' url. Not sure if it is caused by temporary DNS issue but at some point the package starts throwing errors like below. At that time 'dig theurl.com' resolves url properly, but the lib got stuck after first err and the only option is to restart the node, which helps. I will try to add static url to /etc/hosts first then I will check that  {"family": 4} option.

Some details:
System: os X sierra
Node: v5.10.1
Request options:
{     followRedirect: false,  
    uri: “https://theurl.com/apath”,     
    qs: {   goto: “https://ok.path.com”,         
              gotoOnFail: “https://fail.path.com”,     },  
   json: true  }

Error:
{ [RequestError: Error: getaddrinfo ENOTFOUND theurl.com theurl.com:443]
  name: 'RequestError',
  message: 'Error: getaddrinfo ENOTFOUND theurl.com theurl.com:443',
  cause: 
   { [Error: getaddrinfo ENOTFOUND theurl.com theurl.com:443]
     code: 'ENOTFOUND',
     errno: 'ENOTFOUND',
     syscall: 'getaddrinfo',
     hostname: 'theurl.com',
     host: 'theurl.com',
     port: 443 },

**Comment by analog-nico** [comment]
Hi @olexme , the issue you are facing is very low level. `request-promise` uses `request` and `request` uses node's core libraries. The error is thrown by the core libraries. `{ family: 4 }` may help but in your case – since you are requesting the same server over and over again – you may also look into DNS caching. Read the full discussion in [this issue](https://github.com/nodejs/node/issues/5893) to get a good understanding. Finally, since it is a node-level issue you may update to the latest LTS.

**Comment by kilianc** [comment]
@tyleri like this?

```js
require('request-promise-native').defaults({ family: 4 })
```

**Comment by tyleri** [comment]
@kilianc 
I didn't do it that way, but that might work.
I just followed the example here, but added "family: 4" to the options:
https://www.npmjs.com/package/request-promise#post-data-to-a-json-rest-api

**Comment by kilianc** [comment]
I couldn't find any reference in the request source code to a `family` property. I will give this a try, thanks @tyleri

**Comment by tyleri** [comment]
Yes, as mentioned above, it is not documented in request-promise. It seems to be a property of the underlying Node.js libraries that request-promise uses.

**Comment by kilianc** [comment]
@tyleri so it's a pass through property that's why I couldn't find it.

**Comment by tnovau** [comment]
Hey, I'm getting the same issue here, familiy: 4 is not working for me...

OS: Mac OSX Sierra
yarn: 1.12.3
npm: 6.4.1
Node: v8.12.0

Request options: {
body:undefined
headers:Object {x-app-platform: "Android"}
json:true
method:"GET"
uri:"http://someurl/api/v2/version/tag/3.0.1"
}

I'm getting the error only running it with npm (e.g **npm run start:dev**).

{ Error: getaddrinfo ENOTFOUND someurl.com someurl.com:80
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)
     errno: 'ENOTFOUND',
     code: 'ENOTFOUND',
     syscall: 'getaddrinfo',
     hostname: 'someurl.com',
     host: 'someurl.com',
     port: 80 }

**Comment by jstephens7** [comment]
Try passing the url through encodeURI. That was the issue for me.

Request options: {
body:undefined
headers:Object {x-app-platform: "Android"}
json:true
method:"GET"
uri: encodeURI("http://someurl/api/v2/version/tag/3.0.1")
}

**Comment by sakurayang** [comment]
I'm getting the same issue here, both of encodeURI and familiy: 4 are not working for me.
OS: WSL
node: v10.13.0
npm: 
Request options: 
```js
{
body:undefined
headers:undefined
json:true
method:"GET"
uri:"https://s.search.bilibili.com/cate/search?main_ver=v3&pagesize=1&search_type=video&view_type=hot_rank&cate_id=28&page=1&time_from=20190920&time_to=20190921"
}
```
the number of page is over 1000 ,and i write a for loop to get data from page 1 to page n
And I get the error randomly like below

```js
{ RequestError: Error: getaddrinfo ENOTFOUND s.search.bilibili.com s.search.bilibili.com:443
  message:
   'Error: getaddrinfo ENOTFOUND s.search.bilibili.com s.search.bilibili.com:443',
  cause:
   { Error: getaddrinfo ENOTFOUND s.search.bilibili.com s.search.bilibili.com:443
       at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:57:26)
     errno: 'ENOTFOUND',
     code: 'ENOTFOUND',
     syscall: 'getaddrinfo',
     hostname: 's.search.bilibili.com',
     host: 's.search.bilibili.com',
     port: 443 },
  error:
   { Error: getaddrinfo ENOTFOUND s.search.bilibili.com s.search.bilibili.com:443
       at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:57:26)
     errno: 'ENOTFOUND',
     code: 'ENOTFOUND',
     syscall: 'getaddrinfo',
     hostname: 's.search.bilibili.com',
     host: 's.search.bilibili.com',
     port: 443 },
  options:
   { family: 4,
     uri:some_uri,
     method: 'GET',
     callback: [Function: RP$callback],
     transform: undefined,
     simple: true,
     resolveWithFullResponse: false,
     transform2xxOnly: false },
  response: undefined }
```

**Comment by himanshush13** [comment]
hello @tnovau , Have you got anything related to your error, I am too getting the same while running npm start.

**Comment by himanshush13** [comment]
![image](https://user-images.githubusercontent.com/36809136/81793198-a9e6ea00-9526-11ea-9819-3b566c54af4f.png)

This is the error, I am getting on Azure

**Comment by tnovau** [comment]
> hello @tnovau , Have you got anything related to your error, I am too getting the same while running npm start.

Sorry, I'm not using this library anymore.

**Comment by piall** [comment]
> Try passing the url through encodeURI. That was the issue for me.
> 
> Request options: {
> body:undefined
> headers:Object {x-app-platform: "Android"}
> json:true
> method:"GET"
> uri: encodeURI("http://someurl/api/v2/version/tag/3.0.1")
> }

Thanks it worked for me😃
